version: '3.8'

services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - springboot-postgres-network

  app:
    build: .
    environment:
      DB_SERVER: postgresql
      DB_DATABASE: test
      DB_USER: admin
      DB_PASS: 123456
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    networks:
      - springboot-postgres-network

networks:
  springboot-postgres-network:
    driver: bridge
