spring:
  datasource:
    url: jdbc:h2:mem:demo_db
    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASS:sa}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
  h2:
    console.enabled: true

